# Generated by Django 6.1.1 on 2026-09-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='dead_line',
            field=models.DateField(default='2026-09-30'),
        ),
    ]
