# Generated by Django 6.1.1 on 2026-09-09 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rfq_dead_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quatation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_time', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quatations', to='accounts.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quatations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
