# Generated by Django 6.1.1 on 2026-09-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_quatation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quatation',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
